/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaliRouteImport } from './routes/wali'
import { Route as UstadzRouteImport } from './routes/ustadz'
import { Route as SantriRouteImport } from './routes/santri'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaliIndexRouteImport } from './routes/wali/index'
import { Route as UstadzIndexRouteImport } from './routes/ustadz/index'
import { Route as SantriIndexRouteImport } from './routes/santri/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UstadzUjianRouteImport } from './routes/ustadz/ujian'
import { Route as UstadzRiwayatRouteImport } from './routes/ustadz/riwayat'
import { Route as UstadzProfilRouteImport } from './routes/ustadz/profil'
import { Route as UstadzInputRouteImport } from './routes/ustadz/input'
import { Route as AdminUstadzRouteImport } from './routes/admin/ustadz'
import { Route as AdminSantriRouteImport } from './routes/admin/santri'
import { Route as AdminKelasRouteImport } from './routes/admin/kelas'

const WaliRoute = WaliRouteImport.update({
  id: '/wali',
  path: '/wali',
  getParentRoute: () => rootRouteImport,
} as any)
const UstadzRoute = UstadzRouteImport.update({
  id: '/ustadz',
  path: '/ustadz',
  getParentRoute: () => rootRouteImport,
} as any)
const SantriRoute = SantriRouteImport.update({
  id: '/santri',
  path: '/santri',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaliIndexRoute = WaliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WaliRoute,
} as any)
const UstadzIndexRoute = UstadzIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UstadzRoute,
} as any)
const SantriIndexRoute = SantriIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SantriRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UstadzUjianRoute = UstadzUjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzRiwayatRoute = UstadzRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzProfilRoute = UstadzProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzInputRoute = UstadzInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => UstadzRoute,
} as any)
const AdminUstadzRoute = AdminUstadzRouteImport.update({
  id: '/ustadz',
  path: '/ustadz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSantriRoute = AdminSantriRouteImport.update({
  id: '/santri',
  path: '/santri',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKelasRoute = AdminKelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/santri': typeof SantriRouteWithChildren
  '/ustadz': typeof UstadzRouteWithChildren
  '/wali': typeof WaliRouteWithChildren
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/santri': typeof AdminSantriRoute
  '/admin/ustadz': typeof AdminUstadzRoute
  '/ustadz/input': typeof UstadzInputRoute
  '/ustadz/profil': typeof UstadzProfilRoute
  '/ustadz/riwayat': typeof UstadzRiwayatRoute
  '/ustadz/ujian': typeof UstadzUjianRoute
  '/admin/': typeof AdminIndexRoute
  '/santri/': typeof SantriIndexRoute
  '/ustadz/': typeof UstadzIndexRoute
  '/wali/': typeof WaliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/santri': typeof AdminSantriRoute
  '/admin/ustadz': typeof AdminUstadzRoute
  '/ustadz/input': typeof UstadzInputRoute
  '/ustadz/profil': typeof UstadzProfilRoute
  '/ustadz/riwayat': typeof UstadzRiwayatRoute
  '/ustadz/ujian': typeof UstadzUjianRoute
  '/admin': typeof AdminIndexRoute
  '/santri': typeof SantriIndexRoute
  '/ustadz': typeof UstadzIndexRoute
  '/wali': typeof WaliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/santri': typeof SantriRouteWithChildren
  '/ustadz': typeof UstadzRouteWithChildren
  '/wali': typeof WaliRouteWithChildren
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/santri': typeof AdminSantriRoute
  '/admin/ustadz': typeof AdminUstadzRoute
  '/ustadz/input': typeof UstadzInputRoute
  '/ustadz/profil': typeof UstadzProfilRoute
  '/ustadz/riwayat': typeof UstadzRiwayatRoute
  '/ustadz/ujian': typeof UstadzUjianRoute
  '/admin/': typeof AdminIndexRoute
  '/santri/': typeof SantriIndexRoute
  '/ustadz/': typeof UstadzIndexRoute
  '/wali/': typeof WaliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/santri'
    | '/ustadz'
    | '/wali'
    | '/admin/kelas'
    | '/admin/santri'
    | '/admin/ustadz'
    | '/ustadz/input'
    | '/ustadz/profil'
    | '/ustadz/riwayat'
    | '/ustadz/ujian'
    | '/admin/'
    | '/santri/'
    | '/ustadz/'
    | '/wali/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/kelas'
    | '/admin/santri'
    | '/admin/ustadz'
    | '/ustadz/input'
    | '/ustadz/profil'
    | '/ustadz/riwayat'
    | '/ustadz/ujian'
    | '/admin'
    | '/santri'
    | '/ustadz'
    | '/wali'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/santri'
    | '/ustadz'
    | '/wali'
    | '/admin/kelas'
    | '/admin/santri'
    | '/admin/ustadz'
    | '/ustadz/input'
    | '/ustadz/profil'
    | '/ustadz/riwayat'
    | '/ustadz/ujian'
    | '/admin/'
    | '/santri/'
    | '/ustadz/'
    | '/wali/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SantriRoute: typeof SantriRouteWithChildren
  UstadzRoute: typeof UstadzRouteWithChildren
  WaliRoute: typeof WaliRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wali': {
      id: '/wali'
      path: '/wali'
      fullPath: '/wali'
      preLoaderRoute: typeof WaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustadz': {
      id: '/ustadz'
      path: '/ustadz'
      fullPath: '/ustadz'
      preLoaderRoute: typeof UstadzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santri': {
      id: '/santri'
      path: '/santri'
      fullPath: '/santri'
      preLoaderRoute: typeof SantriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wali/': {
      id: '/wali/'
      path: '/'
      fullPath: '/wali/'
      preLoaderRoute: typeof WaliIndexRouteImport
      parentRoute: typeof WaliRoute
    }
    '/ustadz/': {
      id: '/ustadz/'
      path: '/'
      fullPath: '/ustadz/'
      preLoaderRoute: typeof UstadzIndexRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/santri/': {
      id: '/santri/'
      path: '/'
      fullPath: '/santri/'
      preLoaderRoute: typeof SantriIndexRouteImport
      parentRoute: typeof SantriRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ustadz/ujian': {
      id: '/ustadz/ujian'
      path: '/ujian'
      fullPath: '/ustadz/ujian'
      preLoaderRoute: typeof UstadzUjianRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/riwayat': {
      id: '/ustadz/riwayat'
      path: '/riwayat'
      fullPath: '/ustadz/riwayat'
      preLoaderRoute: typeof UstadzRiwayatRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/profil': {
      id: '/ustadz/profil'
      path: '/profil'
      fullPath: '/ustadz/profil'
      preLoaderRoute: typeof UstadzProfilRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/input': {
      id: '/ustadz/input'
      path: '/input'
      fullPath: '/ustadz/input'
      preLoaderRoute: typeof UstadzInputRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/admin/ustadz': {
      id: '/admin/ustadz'
      path: '/ustadz'
      fullPath: '/admin/ustadz'
      preLoaderRoute: typeof AdminUstadzRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/santri': {
      id: '/admin/santri'
      path: '/santri'
      fullPath: '/admin/santri'
      preLoaderRoute: typeof AdminSantriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kelas': {
      id: '/admin/kelas'
      path: '/kelas'
      fullPath: '/admin/kelas'
      preLoaderRoute: typeof AdminKelasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminKelasRoute: typeof AdminKelasRoute
  AdminSantriRoute: typeof AdminSantriRoute
  AdminUstadzRoute: typeof AdminUstadzRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKelasRoute: AdminKelasRoute,
  AdminSantriRoute: AdminSantriRoute,
  AdminUstadzRoute: AdminUstadzRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SantriRouteChildren {
  SantriIndexRoute: typeof SantriIndexRoute
}

const SantriRouteChildren: SantriRouteChildren = {
  SantriIndexRoute: SantriIndexRoute,
}

const SantriRouteWithChildren =
  SantriRoute._addFileChildren(SantriRouteChildren)

interface UstadzRouteChildren {
  UstadzInputRoute: typeof UstadzInputRoute
  UstadzProfilRoute: typeof UstadzProfilRoute
  UstadzRiwayatRoute: typeof UstadzRiwayatRoute
  UstadzUjianRoute: typeof UstadzUjianRoute
  UstadzIndexRoute: typeof UstadzIndexRoute
}

const UstadzRouteChildren: UstadzRouteChildren = {
  UstadzInputRoute: UstadzInputRoute,
  UstadzProfilRoute: UstadzProfilRoute,
  UstadzRiwayatRoute: UstadzRiwayatRoute,
  UstadzUjianRoute: UstadzUjianRoute,
  UstadzIndexRoute: UstadzIndexRoute,
}

const UstadzRouteWithChildren =
  UstadzRoute._addFileChildren(UstadzRouteChildren)

interface WaliRouteChildren {
  WaliIndexRoute: typeof WaliIndexRoute
}

const WaliRouteChildren: WaliRouteChildren = {
  WaliIndexRoute: WaliIndexRoute,
}

const WaliRouteWithChildren = WaliRoute._addFileChildren(WaliRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SantriRoute: SantriRouteWithChildren,
  UstadzRoute: UstadzRouteWithChildren,
  WaliRoute: WaliRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
