/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaliRouteImport } from './routes/wali'
import { Route as UstadzRouteImport } from './routes/ustadz'
import { Route as SantriRouteImport } from './routes/santri'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaliIndexRouteImport } from './routes/wali/index'
import { Route as UstadzIndexRouteImport } from './routes/ustadz/index'
import { Route as SantriIndexRouteImport } from './routes/santri/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UstadzUjianRouteImport } from './routes/ustadz/ujian'
import { Route as UstadzRiwayatRouteImport } from './routes/ustadz/riwayat'
import { Route as UstadzProfilRouteImport } from './routes/ustadz/profil'
import { Route as UstadzPantauRouteImport } from './routes/ustadz/pantau'
import { Route as UstadzInputRouteImport } from './routes/ustadz/input'
import { Route as SantriUjianRouteImport } from './routes/santri/ujian'
import { Route as SantriRiwayatRouteImport } from './routes/santri/riwayat'
import { Route as SantriProfilRouteImport } from './routes/santri/profil'
import { Route as SantriInputRouteImport } from './routes/santri/input'
import { Route as AdminUstadzRouteImport } from './routes/admin/ustadz'
import { Route as AdminUjianRouteImport } from './routes/admin/ujian'
import { Route as AdminSantriRouteImport } from './routes/admin/santri'
import { Route as AdminPengaturanRouteImport } from './routes/admin/pengaturan'
import { Route as AdminLaporanRouteImport } from './routes/admin/laporan'
import { Route as AdminKelasRouteImport } from './routes/admin/kelas'

const WaliRoute = WaliRouteImport.update({
  id: '/wali',
  path: '/wali',
  getParentRoute: () => rootRouteImport,
} as any)
const UstadzRoute = UstadzRouteImport.update({
  id: '/ustadz',
  path: '/ustadz',
  getParentRoute: () => rootRouteImport,
} as any)
const SantriRoute = SantriRouteImport.update({
  id: '/santri',
  path: '/santri',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaliIndexRoute = WaliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WaliRoute,
} as any)
const UstadzIndexRoute = UstadzIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UstadzRoute,
} as any)
const SantriIndexRoute = SantriIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SantriRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UstadzUjianRoute = UstadzUjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzRiwayatRoute = UstadzRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzProfilRoute = UstadzProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzPantauRoute = UstadzPantauRouteImport.update({
  id: '/pantau',
  path: '/pantau',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzInputRoute = UstadzInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => UstadzRoute,
} as any)
const SantriUjianRoute = SantriUjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => SantriRoute,
} as any)
const SantriRiwayatRoute = SantriRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => SantriRoute,
} as any)
const SantriProfilRoute = SantriProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => SantriRoute,
} as any)
const SantriInputRoute = SantriInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => SantriRoute,
} as any)
const AdminUstadzRoute = AdminUstadzRouteImport.update({
  id: '/ustadz',
  path: '/ustadz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUjianRoute = AdminUjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSantriRoute = AdminSantriRouteImport.update({
  id: '/santri',
  path: '/santri',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaporanRoute = AdminLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKelasRoute = AdminKelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/santri': typeof SantriRouteWithChildren
  '/ustadz': typeof UstadzRouteWithChildren
  '/wali': typeof WaliRouteWithChildren
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/santri': typeof AdminSantriRoute
  '/admin/ujian': typeof AdminUjianRoute
  '/admin/ustadz': typeof AdminUstadzRoute
  '/santri/input': typeof SantriInputRoute
  '/santri/profil': typeof SantriProfilRoute
  '/santri/riwayat': typeof SantriRiwayatRoute
  '/santri/ujian': typeof SantriUjianRoute
  '/ustadz/input': typeof UstadzInputRoute
  '/ustadz/pantau': typeof UstadzPantauRoute
  '/ustadz/profil': typeof UstadzProfilRoute
  '/ustadz/riwayat': typeof UstadzRiwayatRoute
  '/ustadz/ujian': typeof UstadzUjianRoute
  '/admin/': typeof AdminIndexRoute
  '/santri/': typeof SantriIndexRoute
  '/ustadz/': typeof UstadzIndexRoute
  '/wali/': typeof WaliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/santri': typeof AdminSantriRoute
  '/admin/ujian': typeof AdminUjianRoute
  '/admin/ustadz': typeof AdminUstadzRoute
  '/santri/input': typeof SantriInputRoute
  '/santri/profil': typeof SantriProfilRoute
  '/santri/riwayat': typeof SantriRiwayatRoute
  '/santri/ujian': typeof SantriUjianRoute
  '/ustadz/input': typeof UstadzInputRoute
  '/ustadz/pantau': typeof UstadzPantauRoute
  '/ustadz/profil': typeof UstadzProfilRoute
  '/ustadz/riwayat': typeof UstadzRiwayatRoute
  '/ustadz/ujian': typeof UstadzUjianRoute
  '/admin': typeof AdminIndexRoute
  '/santri': typeof SantriIndexRoute
  '/ustadz': typeof UstadzIndexRoute
  '/wali': typeof WaliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/santri': typeof SantriRouteWithChildren
  '/ustadz': typeof UstadzRouteWithChildren
  '/wali': typeof WaliRouteWithChildren
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/santri': typeof AdminSantriRoute
  '/admin/ujian': typeof AdminUjianRoute
  '/admin/ustadz': typeof AdminUstadzRoute
  '/santri/input': typeof SantriInputRoute
  '/santri/profil': typeof SantriProfilRoute
  '/santri/riwayat': typeof SantriRiwayatRoute
  '/santri/ujian': typeof SantriUjianRoute
  '/ustadz/input': typeof UstadzInputRoute
  '/ustadz/pantau': typeof UstadzPantauRoute
  '/ustadz/profil': typeof UstadzProfilRoute
  '/ustadz/riwayat': typeof UstadzRiwayatRoute
  '/ustadz/ujian': typeof UstadzUjianRoute
  '/admin/': typeof AdminIndexRoute
  '/santri/': typeof SantriIndexRoute
  '/ustadz/': typeof UstadzIndexRoute
  '/wali/': typeof WaliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/santri'
    | '/ustadz'
    | '/wali'
    | '/admin/kelas'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/santri'
    | '/admin/ujian'
    | '/admin/ustadz'
    | '/santri/input'
    | '/santri/profil'
    | '/santri/riwayat'
    | '/santri/ujian'
    | '/ustadz/input'
    | '/ustadz/pantau'
    | '/ustadz/profil'
    | '/ustadz/riwayat'
    | '/ustadz/ujian'
    | '/admin/'
    | '/santri/'
    | '/ustadz/'
    | '/wali/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/kelas'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/santri'
    | '/admin/ujian'
    | '/admin/ustadz'
    | '/santri/input'
    | '/santri/profil'
    | '/santri/riwayat'
    | '/santri/ujian'
    | '/ustadz/input'
    | '/ustadz/pantau'
    | '/ustadz/profil'
    | '/ustadz/riwayat'
    | '/ustadz/ujian'
    | '/admin'
    | '/santri'
    | '/ustadz'
    | '/wali'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/santri'
    | '/ustadz'
    | '/wali'
    | '/admin/kelas'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/santri'
    | '/admin/ujian'
    | '/admin/ustadz'
    | '/santri/input'
    | '/santri/profil'
    | '/santri/riwayat'
    | '/santri/ujian'
    | '/ustadz/input'
    | '/ustadz/pantau'
    | '/ustadz/profil'
    | '/ustadz/riwayat'
    | '/ustadz/ujian'
    | '/admin/'
    | '/santri/'
    | '/ustadz/'
    | '/wali/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SantriRoute: typeof SantriRouteWithChildren
  UstadzRoute: typeof UstadzRouteWithChildren
  WaliRoute: typeof WaliRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wali': {
      id: '/wali'
      path: '/wali'
      fullPath: '/wali'
      preLoaderRoute: typeof WaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustadz': {
      id: '/ustadz'
      path: '/ustadz'
      fullPath: '/ustadz'
      preLoaderRoute: typeof UstadzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santri': {
      id: '/santri'
      path: '/santri'
      fullPath: '/santri'
      preLoaderRoute: typeof SantriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wali/': {
      id: '/wali/'
      path: '/'
      fullPath: '/wali/'
      preLoaderRoute: typeof WaliIndexRouteImport
      parentRoute: typeof WaliRoute
    }
    '/ustadz/': {
      id: '/ustadz/'
      path: '/'
      fullPath: '/ustadz/'
      preLoaderRoute: typeof UstadzIndexRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/santri/': {
      id: '/santri/'
      path: '/'
      fullPath: '/santri/'
      preLoaderRoute: typeof SantriIndexRouteImport
      parentRoute: typeof SantriRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ustadz/ujian': {
      id: '/ustadz/ujian'
      path: '/ujian'
      fullPath: '/ustadz/ujian'
      preLoaderRoute: typeof UstadzUjianRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/riwayat': {
      id: '/ustadz/riwayat'
      path: '/riwayat'
      fullPath: '/ustadz/riwayat'
      preLoaderRoute: typeof UstadzRiwayatRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/profil': {
      id: '/ustadz/profil'
      path: '/profil'
      fullPath: '/ustadz/profil'
      preLoaderRoute: typeof UstadzProfilRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/pantau': {
      id: '/ustadz/pantau'
      path: '/pantau'
      fullPath: '/ustadz/pantau'
      preLoaderRoute: typeof UstadzPantauRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/input': {
      id: '/ustadz/input'
      path: '/input'
      fullPath: '/ustadz/input'
      preLoaderRoute: typeof UstadzInputRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/santri/ujian': {
      id: '/santri/ujian'
      path: '/ujian'
      fullPath: '/santri/ujian'
      preLoaderRoute: typeof SantriUjianRouteImport
      parentRoute: typeof SantriRoute
    }
    '/santri/riwayat': {
      id: '/santri/riwayat'
      path: '/riwayat'
      fullPath: '/santri/riwayat'
      preLoaderRoute: typeof SantriRiwayatRouteImport
      parentRoute: typeof SantriRoute
    }
    '/santri/profil': {
      id: '/santri/profil'
      path: '/profil'
      fullPath: '/santri/profil'
      preLoaderRoute: typeof SantriProfilRouteImport
      parentRoute: typeof SantriRoute
    }
    '/santri/input': {
      id: '/santri/input'
      path: '/input'
      fullPath: '/santri/input'
      preLoaderRoute: typeof SantriInputRouteImport
      parentRoute: typeof SantriRoute
    }
    '/admin/ustadz': {
      id: '/admin/ustadz'
      path: '/ustadz'
      fullPath: '/admin/ustadz'
      preLoaderRoute: typeof AdminUstadzRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ujian': {
      id: '/admin/ujian'
      path: '/ujian'
      fullPath: '/admin/ujian'
      preLoaderRoute: typeof AdminUjianRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/santri': {
      id: '/admin/santri'
      path: '/santri'
      fullPath: '/admin/santri'
      preLoaderRoute: typeof AdminSantriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/laporan': {
      id: '/admin/laporan'
      path: '/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof AdminLaporanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kelas': {
      id: '/admin/kelas'
      path: '/kelas'
      fullPath: '/admin/kelas'
      preLoaderRoute: typeof AdminKelasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminKelasRoute: typeof AdminKelasRoute
  AdminLaporanRoute: typeof AdminLaporanRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminSantriRoute: typeof AdminSantriRoute
  AdminUjianRoute: typeof AdminUjianRoute
  AdminUstadzRoute: typeof AdminUstadzRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKelasRoute: AdminKelasRoute,
  AdminLaporanRoute: AdminLaporanRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminSantriRoute: AdminSantriRoute,
  AdminUjianRoute: AdminUjianRoute,
  AdminUstadzRoute: AdminUstadzRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SantriRouteChildren {
  SantriInputRoute: typeof SantriInputRoute
  SantriProfilRoute: typeof SantriProfilRoute
  SantriRiwayatRoute: typeof SantriRiwayatRoute
  SantriUjianRoute: typeof SantriUjianRoute
  SantriIndexRoute: typeof SantriIndexRoute
}

const SantriRouteChildren: SantriRouteChildren = {
  SantriInputRoute: SantriInputRoute,
  SantriProfilRoute: SantriProfilRoute,
  SantriRiwayatRoute: SantriRiwayatRoute,
  SantriUjianRoute: SantriUjianRoute,
  SantriIndexRoute: SantriIndexRoute,
}

const SantriRouteWithChildren =
  SantriRoute._addFileChildren(SantriRouteChildren)

interface UstadzRouteChildren {
  UstadzInputRoute: typeof UstadzInputRoute
  UstadzPantauRoute: typeof UstadzPantauRoute
  UstadzProfilRoute: typeof UstadzProfilRoute
  UstadzRiwayatRoute: typeof UstadzRiwayatRoute
  UstadzUjianRoute: typeof UstadzUjianRoute
  UstadzIndexRoute: typeof UstadzIndexRoute
}

const UstadzRouteChildren: UstadzRouteChildren = {
  UstadzInputRoute: UstadzInputRoute,
  UstadzPantauRoute: UstadzPantauRoute,
  UstadzProfilRoute: UstadzProfilRoute,
  UstadzRiwayatRoute: UstadzRiwayatRoute,
  UstadzUjianRoute: UstadzUjianRoute,
  UstadzIndexRoute: UstadzIndexRoute,
}

const UstadzRouteWithChildren =
  UstadzRoute._addFileChildren(UstadzRouteChildren)

interface WaliRouteChildren {
  WaliIndexRoute: typeof WaliIndexRoute
}

const WaliRouteChildren: WaliRouteChildren = {
  WaliIndexRoute: WaliIndexRoute,
}

const WaliRouteWithChildren = WaliRoute._addFileChildren(WaliRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SantriRoute: SantriRouteWithChildren,
  UstadzRoute: UstadzRouteWithChildren,
  WaliRoute: WaliRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
